config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :courses_users
  resources :levels
  resources :courses do
    resources :lessons
  end

  devise_for :users
    get 'users/:id' => 'users#show', as: :user
  # resources :users

  devise_for :teachers
    get 'teachers/:id' => 'teachers#show', as: :teacher
  # resources :teachers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  self.inheritance_column = :_type_disabled
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  after_create :create_lessons, only: [:create]

  has_and_belongs_to_many :users, :join_table => "courses_users"
  belongs_to :level
  belongs_to :teacher
  has_many :lessons, dependent: :destroy
  accepts_nested_attributes_for :lessons

  scope :active, ->{ where.not(active: nil)}
  scope :inactive, ->{ where(active: nil)}

  def create_lessons
    27.times do |l|
      self.lessons.build(title: "Programmed session", status_id: 6)
    end
  end

  #Counts & show in the dashboard graph the courses created from the beggining of times, it needs to be updated to show whatever info we need to display using a chart
  def self.in_progress
    group_by_day(:created_at).count
  end
end

app/models/courses_user.rb
class CoursesUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  validates :status, presence: true

  belongs_to :status

end

app/models/level.rb
class Level < ApplicationRecord
  has_many :courses
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :lessons
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :courses

  scope :active, ->{ where.not(active: true)}
  scope :inactive, ->{ where(active: nil)}
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :courses, :join_table => "courses_users"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  protect_from_forgery

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/courses_users_helper.rb
module CoursesUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_calendar.html.erb
<script>
  $('#calendar').fullCalendar({
    // put your options and callbacks here
    header: { center: 'month,agendaWeek,listWeek' }, // buttons for switching between views
    firstDay: 1, // first day of the week on view
    hiddenDays: [0], // hides sundays
    events: [
    {
      title  : 'event1',
      start  : '2019-12-10'
    },
    {
      title  : 'event2',
      start  : '2019-12-16T12:30:00',
      end    : '2019-12-16T14:00:00',
    },
    {
      title  : 'event3',
      start  : '2019-12-20T12:30:00',
      allDay : false // will make the time show
    }
    ]
  })
</script>

app/views/shared/_chart.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi" %>
<%= javascript_include_tag "application", "chartkick" %>

<% my_chart = Course.in_progress %>
<%= column_chart my_chart, colors: ["#ffb92b"] %>

app/views/shared/_navbar.html.erb
<!-- Header -->
  <header id="header">
    <% if user_signed_in? %>
      <nav class="left">
        <a href="#menu"><span>Menu</span></a>
      </nav>
    <% end %>
    <h1 class="logo"> Course Management System </h1>
    <!-- <nav class="left">
      <button type="button" class="btn btn-secondary"><%= link_to "Log in as a Teacher", new_teacher_session_path %></button>
    </nav> -->
    <nav class="right">
      <button type="button" class="btn btn-secondary"><%= link_to "Log in as a Student", new_user_session_path %></button>
    </nav>
  </header>

<!-- Menu -->
  <nav id="menu">
    <ul class="links">
      <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
    </ul>
    <ul class="actions vertical">
      <li><a href="#" class="button fit">Login</a></li>
    </ul>
  </nav>

app/views/shared/_navbar2.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="<%= root_path %>">Dynamic English Manager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
            <%= current_user.name %>
          <% elsif teacher_signed_in? %>
            <%= current_teacher.name %>
          <% else %>
            Access
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_teacher_session_path %>">Teacher's Log In</a>
          <a class="dropdown-item" href="<%= new_user_session_path %>">Student's Log In</a>

          <% if user_signed_in? || teacher_signed_in? %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="GET">Log Out</a>
          <% end %>

        </div>
      </li>
      <% if user_signed_in? || teacher_signed_in? %>
      <li class="nav-item active">
        <a class="nav-link" href="<%= courses_path %>">My Courses <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Resources</a>
      </li>
      <% elsif %>

      <% end %>

    </ul>
    <!-- aquí puedo mover el dropdown -->
  </div>
</nav>