config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :courses_users
  resources :levels
  resources :courses do
    resources :lessons
  end

  devise_for :users
    get 'users/:id' => 'users#show', as: :user
  # resources :users

  devise_for :teachers
    get 'teachers/:id' => 'teachers#show', as: :teacher
  # resources :teachers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  self.inheritance_column = :_type_disabled
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  after_create :create_lessons, only: [:create]

  has_and_belongs_to_many :users, :join_table => "courses_users"
  belongs_to :level
  belongs_to :teacher
  has_many :lessons, dependent: :destroy
  accepts_nested_attributes_for :lessons

  scope :active, ->{ where.not(active: nil)}
  scope :inactive, ->{ where(active: nil)}

  def create_lessons
    27.times do |l|
      self.lessons.build(title: "Programmed session", status_id: 6)
    end
  end

  #Counts & show in the dashboard graph the courses created from the beggining of times, it needs to be updated to show whatever info we need to display using a chart
  def self.in_progress
    group_by_day(:created_at).count
  end
end

app/models/courses_user.rb
class CoursesUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  validates :status, presence: true

  belongs_to :status

end

app/models/level.rb
class Level < ApplicationRecord
  has_many :courses
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :lessons
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :courses

  scope :active, ->{ where.not(active: true)}
  scope :inactive, ->{ where(active: nil)}
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :courses, :join_table => "courses_users"
end

app/controllers/courses_controller.rb
 class CoursesController < InheritedResources::Base
  protect_from_forgery

  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    if user_signed_in?
      @courses = current_entity.courses.active
    elsif teacher_signed_in?
      @courses = Course.where(courses: {teacher: current_entity, active: true})
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    #avoid users to see other students courses
    if user_signed_in?
      redirect_to courses_path if !@course.users.include?(current_entity)
    elsif teacher_signed_in?
     redirect_to courses_path if @course.teacher != current_entity
   end
    # redirect_to root_path if current_user.teacher? && !@course.users.include?(current_user)
    # @lessons = Lesson.where(course_id: (params[:id])).order('date DESC')
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save

        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  def course_params
    params.require(:course).permit(:title, :start, :finish, :user_ids, :level_id, :teacher_id, :active, :hours, :users, lessons_attributes: [:id, :title, :start, :end, :course_id, :status_id])
    params.require(:user).permit(:user_ids, :user_id)
    params.require(:courses_users).permit(:user_ids)
  end

  def set_course
    @course = Course.find(params[:id])
  end

end

app/controllers/courses_users_controller.rb
class CoursesUsersController < InheritedResources::Base
  protect_from_forgery
  
  private

    def courses_user_params
      params.require(:courses_user).permit(:course_id, :user_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery
  
  def index
  end
end

app/controllers/levels_controller.rb
class LevelsController < InheritedResources::Base
  include ActiveModel::MassAssignmentSecurity
  protect_from_forgery

def create
end

  private

    def level_params
      sanitize_for_mass_assignment(params.require(:level).permit(:title, :code, :description))
    end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  protect_from_forgery

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/courses_users_helper.rb
module CoursesUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses_users/_form.html.erb
<%= form_with(model: courses_user, local: true) do |form| %>
  <% if courses_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(courses_user.errors.count, "error") %> prohibited this courses_user from being saved:</h2>

      <ul>
      <% courses_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses_users/edit.html.erb
<h1>Editing Courses User</h1>

<%= render 'form', courses_user: @courses_user %>

<%= link_to 'Show', @courses_user %> |
<%= link_to 'Back', courses_users_path %>

app/views/courses_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses Users</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses_users.each do |courses_user| %>
      <tr>
        <td><%= courses_user.course %></td>
        <td><%= courses_user.user %></td>
        <td><%= link_to 'Show', courses_user %></td>
        <td><%= link_to 'Edit', edit_courses_user_path(courses_user) %></td>
        <td><%= link_to 'Destroy', courses_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Courses User', new_courses_user_path %>

app/views/courses_users/new.html.erb
<h1>New Courses User</h1>

<%= render 'form', courses_user: @courses_user %>

<%= link_to 'Back', courses_users_path %>

app/views/courses_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @courses_user.course %>
</p>

<p>
  <strong>User:</strong>
  <%= @courses_user.user %>
</p>

<%= link_to 'Edit', edit_courses_user_path(@courses_user) %> |
<%= link_to 'Back', courses_users_path %>